"""
WorkMatch Pro v4 — Seed Dataset (Part 2: Transport, Domestic, Food, Agriculture)
"""

# ══ GIG DELIVERY — NCO 8321 ══
GIG_DELIVERY = [
    {"nco":"8321","sector":"Transport","title":"Delivery Rider (Swiggy)","cat":"Gig Delivery","loc":"Hyderabad","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"8th pass","exp":"0-2 yrs","co":"Swiggy","vehicle":"two-wheeler","migrant":"yes","skills":"delivery rider bike motorcycle scooter food Swiggy GPS route customer doorstep last mile gig daily payout"},
    {"nco":"8321","sector":"Transport","title":"Delivery Rider (Zomato)","cat":"Gig Delivery","loc":"Mumbai","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"8th pass","exp":"0-2 yrs","co":"Zomato","vehicle":"two-wheeler","migrant":"yes","skills":"delivery rider Zomato food parcel bike GPS route OTP doorstep customer gig partner dark store"},
    {"nco":"8321","sector":"Transport","title":"Delivery Rider (Blinkit)","cat":"Gig Delivery","loc":"Delhi","sal":"₹13000-19000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"8th pass","exp":"0-2 yrs","co":"Blinkit","vehicle":"two-wheeler","migrant":"yes","skills":"Blinkit quick commerce 10-minute delivery grocery bike rider dark store route quick delivery"},
    {"nco":"8321","sector":"Transport","title":"Delivery Rider (Amazon Flex)","cat":"Gig Delivery","loc":"Bangalore","sal":"₹14000-20000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"10th pass","exp":"0-2 yrs","co":"Amazon Flex","vehicle":"two-wheeler","migrant":"yes","skills":"Amazon delivery rider Flipkart parcel two-wheeler route GPS OTP last mile logistics flex daily"},
    {"nco":"8321","sector":"Transport","title":"E-Commerce Delivery Boy","cat":"Gig Delivery","loc":"Kolkata","sal":"₹10000-15000/mo","sal_type":"monthly","work_type":"Full-time","edu":"8th pass","exp":"0-1 yrs","co":"Ekart","vehicle":"two-wheeler","migrant":"yes","skills":"delivery boy parcel two-wheeler scooter route OTP Flipkart Meesho Myntra last mile daily"},
    {"nco":"8321","sector":"Transport","title":"Delivery Partner (Dunzo)","cat":"Gig Delivery","loc":"Bangalore","sal":"₹11000-16000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"8th pass","exp":"0-1 yrs","co":"Dunzo","vehicle":"two-wheeler","migrant":"yes","skills":"hyperlocal delivery Dunzo quick commerce bike grocery pharmacy errand pickup drop gig"},
    {"nco":"8321","sector":"Transport","title":"Milk Delivery (Morning Route)","cat":"Gig Delivery","loc":"Pune","sal":"₹8000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Milkbasket","vehicle":"two-wheeler","migrant":"no","skills":"milk delivery morning route dairy subscription doorstep early morning regular customer doodh"},
    {"nco":"8321","sector":"Transport","title":"Grocery Delivery (Bigbasket)","cat":"Gig Delivery","loc":"Chennai","sal":"₹12000-17000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"8th pass","exp":"0-1 yrs","co":"Bigbasket","vehicle":"two-wheeler","migrant":"yes","skills":"grocery delivery Bigbasket Zepto online grocery route bike OTP customer home delivery slots"},
]

# ══ DRIVER — NCO 8322, 8332 ══
DRIVER = [
    {"nco":"8322","sector":"Transport","title":"Personal Driver","cat":"Driver","loc":"Mumbai","sal":"₹700-950/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"2-5 yrs","co":"Private","vehicle":"four-wheeler","migrant":"yes","skills":"personal driver car LMV GPS navigation city outstation employer family punctual trusted"},
    {"nco":"8322","sector":"Transport","title":"Personal Driver","cat":"Driver","loc":"Delhi","sal":"₹15000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"2-5 yrs","co":"Private","vehicle":"four-wheeler","migrant":"yes","skills":"personal driver car GPS city NCR outstation employer trusted good driver licence"},
    {"nco":"8322","sector":"Transport","title":"Cab Driver (Ola/Uber)","cat":"Driver","loc":"Mumbai","sal":"₹18000-28000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"10th pass","exp":"2-5 yrs","co":"Ola","vehicle":"four-wheeler","migrant":"yes","skills":"cab driver Ola Uber app taxi four-wheeler AC GPS passenger city airport hotel corporate rating"},
    {"nco":"8322","sector":"Transport","title":"Cab Driver (Ola/Uber)","cat":"Driver","loc":"Bangalore","sal":"₹20000-30000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"10th pass","exp":"2-5 yrs","co":"Uber","vehicle":"four-wheeler","migrant":"yes","skills":"cab driver Ola Uber app tech city IT corporate airport GPS navigation Bangalore"},
    {"nco":"8332","sector":"Transport","title":"Truck Driver (HMV)","cat":"Driver","loc":"Chennai","sal":"₹900-1400/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"3-7 yrs","co":"DHL","vehicle":"four-wheeler","migrant":"yes","skills":"truck driver lorry tipper tanker HMV heavy goods transport highway licence logbook freight national permit long route"},
    {"nco":"8332","sector":"Transport","title":"Truck Driver","cat":"Driver","loc":"Ludhiana","sal":"₹900-1400/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"3-7 yrs","co":"Transport Co","vehicle":"four-wheeler","migrant":"yes","skills":"truck driver HMV LMV goods transport highway Punjab freight national permit lorry"},
    {"nco":"8321","sector":"Transport","title":"Auto Rickshaw Driver","cat":"Driver","loc":"Delhi","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"8th pass","exp":"1-3 yrs","co":"Self-employed","vehicle":"four-wheeler","migrant":"yes","skills":"auto rickshaw three-wheeler city local passenger Ola meter CNG app-based city transport"},
    {"nco":"8321","sector":"Transport","title":"Auto Rickshaw Driver","cat":"Driver","loc":"Bangalore","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"8th pass","exp":"1-3 yrs","co":"Ola Auto","vehicle":"four-wheeler","migrant":"yes","skills":"auto rickshaw three-wheeler city passenger Ola Rapido app meter CNG Namma Auto"},
    {"nco":"8322","sector":"Transport","title":"School Van Driver","cat":"Driver","loc":"Noida","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"2-4 yrs","co":"School","vehicle":"four-wheeler","migrant":"no","skills":"school van driver children safety route morning drop pickup responsible trusted license"},
    {"nco":"8332","sector":"Transport","title":"JCB / Excavator Operator","cat":"Driver","loc":"Hyderabad","sal":"₹700-1200/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-5 yrs","co":"Construction","vehicle":"four-wheeler","migrant":"yes","skills":"JCB excavator operator earthmoving digging foundation trenching soil removal construction heavy machine"},
]

# ══ DOMESTIC (CLEANING) — NCO 9111 ══
DOMESTIC_CLEANING = [
    {"nco":"9111","sector":"Domestic","title":"Live-In Maid","cat":"Domestic (Cleaning)","loc":"Chennai","sal":"₹8000-15000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"UrbanClap","vehicle":"no","migrant":"yes","skills":"live-in maid domestic cooking cleaning mopping sweeping washing dishes laundry ironing childcare bai ghar"},
    {"nco":"9111","sector":"Domestic","title":"Part-Time Maid","cat":"Domestic (Cleaning)","loc":"Mumbai","sal":"₹5000-9000/mo","sal_type":"monthly","work_type":"Part-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"part-time maid bai cleaning sweeping mopping utensils jhadu pocha 2-3 ghar morning kamwali"},
    {"nco":"9111","sector":"Domestic","title":"Part-Time Maid","cat":"Domestic (Cleaning)","loc":"Bangalore","sal":"₹4000-8000/mo","sal_type":"monthly","work_type":"Part-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"part-time maid morning bai 2 hours cleaning sweeping mopping utensils jhadu pocha ghar"},
    {"nco":"9111","sector":"Domestic","title":"Part-Time Maid","cat":"Domestic (Cleaning)","loc":"Delhi","sal":"₹4500-8500/mo","sal_type":"monthly","work_type":"Part-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"part-time maid bai cleaning sweeping mopping kitchen utensils housework Delhi NCR safai"},
    {"nco":"9111","sector":"Domestic","title":"Part-Time Maid","cat":"Domestic (Cleaning)","loc":"Hyderabad","sal":"₹4000-7500/mo","sal_type":"monthly","work_type":"Part-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"part-time maid cleaning sweeping mopping utensils bai domestic"},
    {"nco":"9111","sector":"Domestic","title":"Full-Time Housekeeper","cat":"Domestic (Cleaning)","loc":"Pune","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"HomeTriangle","vehicle":"no","migrant":"yes","skills":"full time maid housekeeper cooking cleaning laundry ironing deep clean all duties household"},
    {"nco":"9111","sector":"Domestic","title":"Deep Cleaning Worker","cat":"Domestic (Cleaning)","loc":"Bangalore","sal":"₹800-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-2 yrs","co":"Urban Company","vehicle":"no","migrant":"yes","skills":"deep cleaning sofa carpet bathroom kitchen floor scrubbing disinfection post-construction cleaning one-time"},
]

# ══ DOMESTIC (COOK/CARE) — NCO 9112 ══
DOMESTIC_COOKCARE = [
    {"nco":"9112","sector":"Domestic","title":"Home Cook","cat":"Domestic (Cook/Care)","loc":"Pune","sal":"₹6000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-4 yrs","co":"Cook4Me","vehicle":"no","migrant":"yes","skills":"home cook Indian food family meals roti sabzi dal rice biryani Maharashtrian North South Indian khana"},
    {"nco":"9112","sector":"Domestic","title":"Home Cook","cat":"Domestic (Cook/Care)","loc":"Bangalore","sal":"₹7000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-4 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"home cook daily cooking roti sabzi dal rice lunch dinner South North Indian Bangalore family"},
    {"nco":"9112","sector":"Domestic","title":"Home Cook","cat":"Domestic (Cook/Care)","loc":"Mumbai","sal":"₹7000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-4 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"home cook Mumbai roti sabzi dal rice fish seafood Maharashtrian family meals khana pakana"},
    {"nco":"9112","sector":"Domestic","title":"Tiffin Cook / Dabba Service","cat":"Domestic (Cook/Care)","loc":"Mumbai","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Part-time","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"no","migrant":"no","skills":"tiffin dabba cook homemade food delivery office worker lunch daily 25-50 dabbas roti sabzi dal"},
    {"nco":"9111","sector":"Domestic","title":"Babysitter / Nanny","cat":"Domestic (Cook/Care)","loc":"Mumbai","sal":"₹7000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"CareWorld","vehicle":"no","migrant":"yes","skills":"babysitter nanny childcare infant toddler baby feeding bathing activity school pickup caring"},
    {"nco":"9111","sector":"Domestic","title":"Elder Care Attendant","cat":"Domestic (Cook/Care)","loc":"Delhi","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-4 yrs","co":"Nightingales","vehicle":"no","migrant":"yes","skills":"elder care senior attendant bed-ridden patient medication food hygiene support old age"},
    {"nco":"9111","sector":"Domestic","title":"Elder Care Attendant","cat":"Domestic (Cook/Care)","loc":"Bangalore","sal":"₹9000-15000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-4 yrs","co":"Portea","vehicle":"no","migrant":"yes","skills":"elder care senior care attendant nursing aide medication daily living aging buzurg"},
    {"nco":"9112","sector":"Domestic","title":"Driver cum Household Helper","cat":"Domestic (Cook/Care)","loc":"Noida","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"2-4 yrs","co":"Private","vehicle":"four-wheeler","migrant":"yes","skills":"driver helper all-rounder household car drive errands shopping market cook light work trusted"},
]

# ══ FOOD & HOSPITALITY — NCO 5120, 5131 ══
FOOD_HOSPITALITY = [
    {"nco":"5120","sector":"Hospitality","title":"Restaurant Cook","cat":"Food & Hospitality","loc":"Mumbai","sal":"₹700-1100/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Taj Hotels","vehicle":"no","migrant":"yes","skills":"restaurant hotel kitchen cook food preparation curry tandoor marination chopping hygiene chef dal sabzi"},
    {"nco":"5120","sector":"Hospitality","title":"Dhaba Cook","cat":"Food & Hospitality","loc":"Ludhiana","sal":"₹500-800/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Dhaba","vehicle":"no","migrant":"yes","skills":"dhaba cook highway roadside dal makhani roti tandoor sabzi rice paratha food driver khana simple"},
    {"nco":"5120","sector":"Hospitality","title":"Dhaba Cook","cat":"Food & Hospitality","loc":"Delhi","sal":"₹550-850/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Dhaba","vehicle":"no","migrant":"yes","skills":"dhaba cook roadside North Indian Punjabi roti dal sabzi naan simple food street"},
    {"nco":"5131","sector":"Hospitality","title":"Waiter / Steward","cat":"Food & Hospitality","loc":"Mumbai","sal":"₹450-750/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Restaurant","vehicle":"no","migrant":"yes","skills":"waiter food serving table order restaurant customer service bill hospitality menu banquet"},
    {"nco":"5131","sector":"Hospitality","title":"Waiter","cat":"Food & Hospitality","loc":"Goa","sal":"₹400-700/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Marriott","vehicle":"no","migrant":"yes","skills":"waiter steward restaurant hotel banquet food serving table order customer bill hospitality tray tips"},
    {"nco":"5120","sector":"Hospitality","title":"Catering Worker","cat":"Food & Hospitality","loc":"Delhi","sal":"₹500-800/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Catering Co","vehicle":"no","migrant":"yes","skills":"catering wedding event function food large scale bulk cooking serving cleaning helper"},
    {"nco":"5120","sector":"Hospitality","title":"Hotel Kitchen Helper","cat":"Food & Hospitality","loc":"Hyderabad","sal":"₹8000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Hotel","vehicle":"no","migrant":"yes","skills":"kitchen helper washing dishes cleaning chopping prep work hygiene hotel restaurant support"},
]

# ══ AGRICULTURE (CROPS) — NCO 9211 ══
AGRICULTURE_CROPS = [
    {"nco":"9211","sector":"Agriculture","title":"Farm Worker / Khet Mazdoor","cat":"Agriculture (Crops)","loc":"Nashik","sal":"₹350-550/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-3 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"farm worker khet mazdoor crop harvesting sowing planting weeding irrigation field wheat rice sugarcane cotton vegetable"},
    {"nco":"9211","sector":"Agriculture","title":"Farm Worker / Khet Mazdoor","cat":"Agriculture (Crops)","loc":"Sehore","sal":"₹300-500/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-3 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"farm worker khet mazdoor crop harvest sow plant weed field Madhya Pradesh wheat paddy"},
    {"nco":"9211","sector":"Agriculture","title":"Farm Worker / Khet Mazdoor","cat":"Agriculture (Crops)","loc":"Tezpur","sal":"₹300-480/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-3 yrs","co":"Tea Garden","vehicle":"no","migrant":"yes","skills":"farm worker plantation tea Assam field labour harvest picking khet seasonal"},
    {"nco":"9211","sector":"Agriculture","title":"Farm Worker (Seasonal)","cat":"Agriculture (Crops)","loc":"Punjab","sal":"₹400-600/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-2 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"seasonal farm worker wheat paddy harvesting combine machine helper sowing Punjab seasonal labour"},
    {"nco":"9211","sector":"Agriculture","title":"Farm Worker","cat":"Agriculture (Crops)","loc":"Maharashtra","sal":"₹350-530/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-2 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"farm worker sugarcane cotton onion grape harvesting Maharashtra khet seasonal labour"},
    {"nco":"8341","sector":"Agriculture","title":"Tractor Operator","cat":"Agriculture (Crops)","loc":"Ludhiana","sal":"₹500-800/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-5 yrs","co":"Farm Owner","vehicle":"four-wheeler","migrant":"no","skills":"tractor operator ploughing tilling cultivator sowing seed drill harvesting combine thresher farm machinery Punjab"},
    {"nco":"9211","sector":"Agriculture","title":"Irrigation Worker","cat":"Agriculture (Crops)","loc":"Nashik","sal":"₹400-600/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"irrigation canal watering sprinkler drip water pump field crop water management khet"},
    {"nco":"9211","sector":"Agriculture","title":"Pesticide Applicator","cat":"Agriculture (Crops)","loc":"Hyderabad","sal":"₹400-600/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Farm Owner","vehicle":"two-wheeler","migrant":"yes","skills":"pesticide spray chemical application crop protection pump field agriculture pest control"},
    {"nco":"9211","sector":"Agriculture","title":"Floriculture Worker","cat":"Agriculture (Crops)","loc":"Pune","sal":"₹350-500/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Farm Owner","vehicle":"no","migrant":"yes","skills":"flower farm rose marigold cutting sorting packing export greenhouse floriculture harvesting"},
]

# ══ AGRICULTURE (LIVESTOCK) — NCO 6121 ══
AGRICULTURE_LIVESTOCK = [
    {"nco":"6121","sector":"Agriculture","title":"Dairy Farm Worker","cat":"Agriculture (Livestock)","loc":"Anand","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Amul","vehicle":"two-wheeler","migrant":"no","skills":"dairy farm cow buffalo milk milking fodder feeding cleaning shed animal care doodh collection Amul Gujarat gaushala"},
    {"nco":"6121","sector":"Agriculture","title":"Dairy Farm Worker","cat":"Agriculture (Livestock)","loc":"Ludhiana","sal":"₹8000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Milk Union","vehicle":"two-wheeler","migrant":"no","skills":"dairy farm cow buffalo milking fodder care doodh Punjab milk collection gaushala"},
    {"nco":"6121","sector":"Agriculture","title":"Poultry Farm Worker","cat":"Agriculture (Livestock)","loc":"Hyderabad","sal":"₹7000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Suguna Foods","vehicle":"no","migrant":"yes","skills":"poultry farm chicken broiler layer feeding cleaning egg collection vaccination murgi farm worker"},
    {"nco":"6121","sector":"Agriculture","title":"Poultry Farm Worker","cat":"Agriculture (Livestock)","loc":"Bangalore","sal":"₹7000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Poultry Farm","vehicle":"no","migrant":"yes","skills":"poultry farm broiler chicken egg feeding cleaning murgi farm worker Karnataka"},
    {"nco":"6121","sector":"Agriculture","title":"Goat Herder","cat":"Agriculture (Livestock)","loc":"Sehore","sal":"₹300-450/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-3 yrs","co":"Local","vehicle":"no","migrant":"no","skills":"goat sheep livestock grazing herding pasture field pashupalan"},
    {"nco":"6122","sector":"Agriculture","title":"Fisherman (Coastal)","cat":"Agriculture (Livestock)","loc":"Goa","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Coastal Cooperative","vehicle":"no","migrant":"no","skills":"fishing sea boat net catch macchi fish coastal cooperative harbour"},
]

# ══ AGRICULTURE (VENDOR) — NCO 9214 ══
AGRICULTURE_VENDOR = [
    {"nco":"9214","sector":"Agriculture","title":"Vegetable / Fruit Vendor","cat":"Agriculture (Vendor)","loc":"Mumbai","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"sabzi vendor vegetable fruit thela cart wholesale retail weighing fresh produce mandi supply"},
    {"nco":"9214","sector":"Agriculture","title":"Vegetable / Fruit Vendor","cat":"Agriculture (Vendor)","loc":"Delhi","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"sabzi mandi vegetable fruit vendor thela retail wholesale daily market"},
    {"nco":"9214","sector":"Agriculture","title":"Fish Monger / Fish Seller","cat":"Agriculture (Vendor)","loc":"Mumbai","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"fish monger macchi seller fresh fish market wholesale retail cleaning gutting weighing Mumbai"},
    {"nco":"9214","sector":"Agriculture","title":"Fish Monger / Fish Seller","cat":"Agriculture (Vendor)","loc":"Kochi","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"no","skills":"fish monger macchi seller Kerala fish market wholesale retail weighing cleaning harbour"},
]
