"""
WorkMatch Pro v4 — Seed Dataset (Part 1: Plumbing through Masonry)
All jobs anchored to eShram NCO codes. Salaries from MoSPI PLFS 2022-23 / NITI Aayog / ILO.
"""

# ══ PLUMBING — NCO 7126 ══
PLUMBING = [
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Mumbai","sal":"₹700-1000/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Urban Company","vehicle":"two-wheeler","migrant":"yes","skills":"plumber water pipe tap sink drain toilet bathroom kitchen geyser sewage fitting choke burst joint wrench pipe leak repair"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Delhi","sal":"₹750-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"JustDial","vehicle":"two-wheeler","migrant":"yes","skills":"plumber tap water pipe fitting drain bathroom kitchen sewage nal thik pipe leak repair Delhi NCR"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Bangalore","sal":"₹750-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Sulekha","vehicle":"two-wheeler","migrant":"yes","skills":"plumber water pipe tap toilet geyser shower drain fitting installation repair Bangalore"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Hyderabad","sal":"₹650-950/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"0-2 yrs","co":"UrbanClap","vehicle":"two-wheeler","migrant":"yes","skills":"plumber pipe tap water geyser shower drain repair installation leak fix"},
    {"nco":"7126","sector":"Construction","title":"Senior Plumber","cat":"Plumbing","loc":"Pune","sal":"₹1000-1400/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"3-6 yrs","co":"Sulekha","vehicle":"two-wheeler","migrant":"yes","skills":"senior plumber team lead commercial building sewer water line pipe layout supervisor skilled foreman project"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Chennai","sal":"₹700-1000/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"plumber water supply fitting bathroom kitchen drain household commercial pipe"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Surat","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"plumber water supply pipe fitting bathroom kitchen drain sewage Gujarat"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Jaipur","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"plumber pipe tap water bathroom geyser fitting Rajasthan"},
    {"nco":"7126","sector":"Construction","title":"Plumber","cat":"Plumbing","loc":"Kolkata","sal":"₹650-950/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"JustDial","vehicle":"two-wheeler","migrant":"yes","skills":"plumber water pipe drain bathroom kitchen repair fitting West Bengal"},
    {"nco":"7126","sector":"Construction","title":"Plumbing Supervisor","cat":"Plumbing","loc":"Bangalore","sal":"₹1200-1800/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"5-8 yrs","co":"L&T","vehicle":"two-wheeler","migrant":"no","skills":"plumbing supervisor site drainage water supply sewage commercial building team quality inspection"},
    {"nco":"7126","sector":"Construction","title":"Drainage / Sewage Worker","cat":"Plumbing","loc":"Delhi","sal":"₹550-850/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Municipal","vehicle":"no","migrant":"yes","skills":"drainage sewage nala cleaning sewer line unblock underground pipe civil municipal maintenance choked"},
    {"nco":"7126","sector":"Construction","title":"Water Tanker Driver","cat":"Plumbing","loc":"Hyderabad","sal":"₹600-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Private","vehicle":"four-wheeler","migrant":"yes","skills":"water tanker supply delivery driver construction site colony water shortage supply"},
    {"nco":"7126","sector":"Construction","title":"Plumber (Geyser/Boiler)","cat":"Plumbing","loc":"Delhi","sal":"₹800-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"2-4 yrs","co":"Racold","vehicle":"two-wheeler","migrant":"no","skills":"geyser installation repair solar water heater boiler plumbing gas connection fitting"},
]

# ══ ELECTRICAL WORK — NCO 7411 ══
ELECTRICAL = [
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Delhi","sal":"₹800-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-4 yrs","co":"JustDial","vehicle":"two-wheeler","migrant":"yes","skills":"electrician wiring installation home apartment switch socket fan MCB circuit breaker fuse inverter light fitting repair"},
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Mumbai","sal":"₹850-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-4 yrs","co":"Urban Company","vehicle":"two-wheeler","migrant":"yes","skills":"electrician wiring MCB socket fan light inverter power distribution panel fitting repair home office"},
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Bangalore","sal":"₹900-1300/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"2-5 yrs","co":"Sulekha","vehicle":"two-wheeler","migrant":"yes","skills":"electrician wiring home office building light fan socket switch repair installation"},
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Hyderabad","sal":"₹800-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-4 yrs","co":"UrbanClap","vehicle":"two-wheeler","migrant":"no","skills":"electrician wiring switch socket fan MCB inverter light fitting installation repair"},
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Pune","sal":"₹850-1250/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"2-4 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"electrician wiring home building fan light switch repair ITI Maharashtra"},
    {"nco":"7411","sector":"Construction","title":"Electrician (ITI Certified)","cat":"Electrical Work","loc":"Chennai","sal":"₹900-1300/day","sal_type":"daily","work_type":"Full-time","edu":"ITI-Diploma","exp":"2-5 yrs","co":"Thermax","vehicle":"two-wheeler","migrant":"yes","skills":"electrician ITI wiring motor pump panel PLC inverter transformer factory industrial maintenance"},
    {"nco":"7411","sector":"Construction","title":"Electrician","cat":"Electrical Work","loc":"Sehore","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"8th pass","exp":"1-3 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"no","skills":"electrician wiring light switch fan repair household small town rural"},
    {"nco":"7411","sector":"Construction","title":"Electrical Wireman","cat":"Electrical Work","loc":"Ranchi","sal":"₹700-1000/day","sal_type":"daily","work_type":"Full-time","edu":"ITI-Diploma","exp":"2-4 yrs","co":"L&T","vehicle":"two-wheeler","migrant":"yes","skills":"wireman electrical wiring conduit cable laying panel switch MCB industrial building"},
    {"nco":"7411","sector":"Construction","title":"Solar Panel Installer","cat":"Electrical Work","loc":"Jaipur","sal":"₹700-1100/day","sal_type":"daily","work_type":"Full-time","edu":"ITI-Diploma","exp":"1-3 yrs","co":"Tata Power Solar","vehicle":"two-wheeler","migrant":"no","skills":"solar panel installation rooftop electrical wiring inverter battery DC AC grid renewable energy"},
    {"nco":"7411","sector":"Construction","title":"Lineman","cat":"Electrical Work","loc":"Lucknow","sal":"₹700-1000/day","sal_type":"daily","work_type":"Full-time","edu":"ITI-Diploma","exp":"2-4 yrs","co":"UPPCL","vehicle":"two-wheeler","migrant":"no","skills":"lineman overhead line electrical pole transformer DISCOM power distribution maintenance safety"},
]

# ══ CARPENTRY — NCO 7115 ══
CARPENTRY = [
    {"nco":"7115","sector":"Construction","title":"Carpenter","cat":"Carpentry","loc":"Bangalore","sal":"₹700-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"2-5 yrs","co":"Sulekha","vehicle":"two-wheeler","migrant":"yes","skills":"carpenter furniture door window frame wood cutting polishing plywood modular kitchen cabinet wardrobe joinery"},
    {"nco":"7115","sector":"Construction","title":"Carpenter","cat":"Carpentry","loc":"Mumbai","sal":"₹750-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"2-4 yrs","co":"Urban Company","vehicle":"two-wheeler","migrant":"yes","skills":"carpenter wood furniture door window frame modular kitchen plywood wardrobe polish fitting"},
    {"nco":"7115","sector":"Construction","title":"Furniture Carpenter","cat":"Carpentry","loc":"Jaipur","sal":"₹700-1000/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"Furniture Workshop","vehicle":"no","migrant":"yes","skills":"furniture carpenter sofa chair table wood making finishing polish Rajasthani craft design"},
    {"nco":"7115","sector":"Construction","title":"Shuttering Carpenter","cat":"Carpentry","loc":"Hyderabad","sal":"₹700-1000/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"NCC Ltd","vehicle":"no","migrant":"yes","skills":"shuttering carpenter formwork plywood centering slab column beam RCC mould deshuttering construction"},
    {"nco":"7115","sector":"Construction","title":"Carpenter","cat":"Carpentry","loc":"Delhi","sal":"₹750-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"2-5 yrs","co":"UrbanClap","vehicle":"two-wheeler","migrant":"yes","skills":"carpenter furniture kitchen wardrobe wood cutting plywood modular panel fitting"},
    {"nco":"7115","sector":"Construction","title":"Carpenter","cat":"Carpentry","loc":"Lucknow","sal":"₹600-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"2-5 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"carpenter wood door window furniture repair polish fitting traditional"},
    {"nco":"7115","sector":"Construction","title":"Modular Kitchen Installer","cat":"Carpentry","loc":"Pune","sal":"₹900-1400/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"3-5 yrs","co":"Hafele","vehicle":"two-wheeler","migrant":"no","skills":"modular kitchen installation carpenter cabinet drawer hinge fitting plywood carcass laminate"},
]

# ══ AC & APPLIANCE REPAIR — NCO 7233 ══
AC_APPLIANCE = [
    {"nco":"7233","sector":"Electronics","title":"AC Technician","cat":"AC & Appliance Repair","loc":"Delhi","sal":"₹900-1400/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-3 yrs","co":"Voltas","vehicle":"two-wheeler","migrant":"no","skills":"AC air conditioner repair service installation gas charging compressor filter split window inverter cooling HVAC refrigeration"},
    {"nco":"7233","sector":"Electronics","title":"AC Technician","cat":"AC & Appliance Repair","loc":"Mumbai","sal":"₹900-1400/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-3 yrs","co":"Daikin","vehicle":"two-wheeler","migrant":"no","skills":"AC split window inverter gas filling compressor repair service installation cooling HVAC refrigerant"},
    {"nco":"7233","sector":"Electronics","title":"AC Technician","cat":"AC & Appliance Repair","loc":"Hyderabad","sal":"₹850-1300/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-3 yrs","co":"Urban Company","vehicle":"two-wheeler","migrant":"no","skills":"AC refrigerator washing machine repair service appliance cooling compressor gas charging"},
    {"nco":"7233","sector":"Electronics","title":"Home Appliance Technician","cat":"AC & Appliance Repair","loc":"Bangalore","sal":"₹700-1100/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"2-4 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"no","skills":"washing machine refrigerator geyser microwave TV repair appliance technician electronics service home"},
    {"nco":"7233","sector":"Electronics","title":"Mobile Repair Technician","cat":"AC & Appliance Repair","loc":"Hyderabad","sal":"₹500-900/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Self-employed","vehicle":"no","migrant":"no","skills":"mobile phone repair screen replacement battery charging port motherboard PCB soldering software flash Samsung iPhone Android"},
    {"nco":"7233","sector":"Electronics","title":"CCTV Installer","cat":"AC & Appliance Repair","loc":"Delhi","sal":"₹700-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-3 yrs","co":"CP Plus","vehicle":"two-wheeler","migrant":"no","skills":"CCTV camera installation security DVR NVR IP camera cable network biometric access control surveillance"},
    {"nco":"7233","sector":"Electronics","title":"TV / LED Repair Technician","cat":"AC & Appliance Repair","loc":"Lucknow","sal":"₹500-800/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Self-employed","vehicle":"no","migrant":"no","skills":"television LED LCD TV repair screen display panel power board remote home electronics"},
    {"nco":"7233","sector":"Electronics","title":"AC Technician","cat":"AC & Appliance Repair","loc":"Jaipur","sal":"₹800-1200/day","sal_type":"daily","work_type":"Gig-Daily","edu":"10th pass","exp":"1-3 yrs","co":"Voltas","vehicle":"two-wheeler","migrant":"no","skills":"AC split window inverter repair service gas filling cooling HVAC Rajasthan summer"},
]

# ══ PAINTING — NCO 7131 ══
PAINTING = [
    {"nco":"7131","sector":"Construction","title":"House Painter","cat":"Painting","loc":"Mumbai","sal":"₹600-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Asian Paints","vehicle":"no","migrant":"yes","skills":"painter wall painting interior exterior emulsion texture putty primer colour brush roller spray residential"},
    {"nco":"7131","sector":"Construction","title":"House Painter","cat":"Painting","loc":"Delhi","sal":"₹650-950/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Nerolac","vehicle":"no","migrant":"yes","skills":"house painter wall painting interior exterior colour putty primer brush roller residential"},
    {"nco":"7131","sector":"Construction","title":"House Painter","cat":"Painting","loc":"Bangalore","sal":"₹650-950/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Berger Paints","vehicle":"no","migrant":"yes","skills":"painter interior exterior emulsion distemper texture putty primer wall ceiling painting residential commercial"},
    {"nco":"7131","sector":"Construction","title":"Waterproofing Specialist","cat":"Painting","loc":"Mumbai","sal":"₹800-1200/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Dr Fixit","vehicle":"no","migrant":"yes","skills":"waterproofing terrace roof bathroom leakage chemical application membrane coating sealant damp proof seepage"},
    {"nco":"7131","sector":"Construction","title":"Texture / Design Painter","cat":"Painting","loc":"Bangalore","sal":"₹800-1300/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"3-5 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"texture paint wall design stencil art 3D decorative wall pattern creative interior painter"},
    {"nco":"7131","sector":"Construction","title":"Interior Painter","cat":"Painting","loc":"Noida","sal":"₹600-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"HomePainter","vehicle":"no","migrant":"yes","skills":"interior painting emulsion putty primer brush roller wall ceiling colour coat finish"},
    {"nco":"7131","sector":"Construction","title":"Spray Painter (Auto)","cat":"Painting","loc":"Ludhiana","sal":"₹650-950/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Auto Paint","vehicle":"no","migrant":"yes","skills":"spray painting automotive car body shop metal gate railing duco finish enamel"},
]

# ══ MASONRY — NCO 7112 / 9313 ══
MASONRY = [
    {"nco":"7112","sector":"Construction","title":"Mason (Rajmistri)","cat":"Masonry","loc":"Delhi","sal":"₹850-1200/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"NCC Ltd","vehicle":"no","migrant":"yes","skills":"mason bricklaying plastering cement wall tiling floor rajmistri masonry pointing leveling skilled mistri nirmaan"},
    {"nco":"7112","sector":"Construction","title":"Mason (Rajmistri)","cat":"Masonry","loc":"Mumbai","sal":"₹900-1200/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"Gammon India","vehicle":"no","migrant":"yes","skills":"mason bricklaying cement plaster concrete tile floor rajmistri mistri wall construction site"},
    {"nco":"7112","sector":"Construction","title":"Mason (Rajmistri)","cat":"Masonry","loc":"Kolkata","sal":"₹800-1100/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"Shapoorji","vehicle":"no","migrant":"yes","skills":"mason bricklaying plastering cement wall tiling floor rajmistri construction West Bengal"},
    {"nco":"7112","sector":"Construction","title":"Mason (Rajmistri)","cat":"Masonry","loc":"Hyderabad","sal":"₹800-1100/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"L&T","vehicle":"no","migrant":"yes","skills":"mason bricklaying cement plaster tile floor construction rajmistri site"},
    {"nco":"9313","sector":"Construction","title":"Site Labourer (Mazdoor)","cat":"Masonry","loc":"Delhi","sal":"₹450-600/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"NCC Ltd","vehicle":"no","migrant":"yes","skills":"site labourer mazdoor cement mixing sand loading unloading bricks digging excavation site cleaning lifting construction unskilled helper"},
    {"nco":"9313","sector":"Construction","title":"Site Labourer (Mazdoor)","cat":"Masonry","loc":"Mumbai","sal":"₹450-620/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Shapoorji","vehicle":"no","migrant":"yes","skills":"labourer mazdoor construction site cement sand brick loading unloading digging helper unskilled building"},
    {"nco":"9313","sector":"Construction","title":"Site Labourer (Mazdoor)","cat":"Masonry","loc":"Nashik","sal":"₹420-580/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Construction","vehicle":"no","migrant":"yes","skills":"mazdoor labourer site construction cement sand digging excavation unskilled helper building daily wage"},
    {"nco":"7112","sector":"Construction","title":"Tile Fixer","cat":"Masonry","loc":"Chennai","sal":"₹700-1000/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"tile fixer tiling floor wall bathroom kitchen vitrified ceramic adhesive grout spacer leveling finishing"},
    {"nco":"7112","sector":"Construction","title":"Bar Bender / Rod Binder","cat":"Masonry","loc":"Mumbai","sal":"₹600-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Gammon India","vehicle":"no","migrant":"yes","skills":"bar bender rod binder iron reinforcement steel rebar bending tying RCC column beam slab iron"},
    {"nco":"7112","sector":"Construction","title":"Welder","cat":"Masonry","loc":"Chennai","sal":"₹700-1100/day","sal_type":"daily","work_type":"Full-time","edu":"ITI-Diploma","exp":"2-4 yrs","co":"L&T","vehicle":"two-wheeler","migrant":"yes","skills":"welder MIG TIG arc gas cutting fabrication steel iron structure pipe industrial workshop welding"},
    {"nco":"9313","sector":"Construction","title":"Brick Kiln Worker","cat":"Masonry","loc":"Patna","sal":"₹350-500/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Brick Kiln","vehicle":"no","migrant":"yes","skills":"brick kiln worker clay moulding firing loading stacking oven bhatta labour seasonal migrant"},
    {"nco":"9313","sector":"Construction","title":"Brick Kiln Worker","cat":"Masonry","loc":"Lucknow","sal":"₹350-500/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Brick Kiln","vehicle":"no","migrant":"yes","skills":"brick kiln bhatta clay moulding loading seasonal construction material maker"},
]
