"""
WorkMatch Pro v4 — Seed Dataset (Part 3: Apparel, Security, Manufacturing, Beauty, Healthcare, BPO, Sales, Street, Waste)
"""

# ══ APPAREL & TEXTILE — NCO 7531, 7533 ══
APPAREL = [
    {"nco":"7531","sector":"Apparel","title":"Tailor (Darzi)","cat":"Apparel & Textile","loc":"Surat","sal":"₹500-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-5 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"tailor darzi stitching sewing cutting blouse salwar kurta shirt trouser measurement fitting alteration machine hand silai"},
    {"nco":"7531","sector":"Apparel","title":"Tailor (Darzi)","cat":"Apparel & Textile","loc":"Jaipur","sal":"₹500-850/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-5 yrs","co":"Self-employed","vehicle":"no","migrant":"no","skills":"tailor darzi stitching cutting blouse salwar kurta measurement fitting alteration Rajasthani silai"},
    {"nco":"7531","sector":"Apparel","title":"Tailor (Darzi)","cat":"Apparel & Textile","loc":"Lucknow","sal":"₹450-800/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-5 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"tailor darzi stitching sewing blouse salwar kurta suit alteration machine hand silai Lucknow"},
    {"nco":"8153","sector":"Apparel","title":"Garment Factory Worker","cat":"Apparel & Textile","loc":"Tiruppur","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"8th pass","exp":"0-2 yrs","co":"Tiruppur Mills","vehicle":"no","migrant":"yes","skills":"garment factory sewing machine stitching cutting fabric textile t-shirt export production line assembly packing"},
    {"nco":"8153","sector":"Apparel","title":"Garment Factory Worker","cat":"Apparel & Textile","loc":"Surat","sal":"₹8000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"8th pass","exp":"0-2 yrs","co":"Textile Mill","vehicle":"no","migrant":"yes","skills":"garment sewing machine textile stitching cutting fabric production line assembly quality packing"},
    {"nco":"7533","sector":"Apparel","title":"Embroidery Worker (Karigari)","cat":"Apparel & Textile","loc":"Lucknow","sal":"₹400-700/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Craft Exports","vehicle":"no","migrant":"no","skills":"embroidery chikankari zardozi hand work fabric thread needle art craft wedding garment export karigari silai"},
    {"nco":"7533","sector":"Apparel","title":"Weaving Worker","cat":"Apparel & Textile","loc":"Varanasi","sal":"₹400-650/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"3-6 yrs","co":"Handloom","vehicle":"no","migrant":"no","skills":"weaving handloom power loom silk cotton saree banarasi warp weft shuttle design pattern traditional bunai"},
    {"nco":"9111","sector":"Apparel","title":"Dry Cleaner / Dhobi","cat":"Apparel & Textile","loc":"Delhi","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"FabCare","vehicle":"no","migrant":"yes","skills":"dry cleaning laundry pressing ironing washing garment stain removal steam iron dhobi kapde"},
]

# ══ SECURITY & FACILITY — NCO 5414 ══
SECURITY = [
    {"nco":"5414","sector":"Security","title":"Security Guard","cat":"Security & Facility","loc":"Delhi","sal":"₹11000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"G4S India","vehicle":"no","migrant":"yes","skills":"security guard gatekeeper watchman patrol entry exit log visitor access control night shift uniform duty chowkidar"},
    {"nco":"5414","sector":"Security","title":"Security Guard","cat":"Security & Facility","loc":"Mumbai","sal":"₹11000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"SIS India","vehicle":"no","migrant":"yes","skills":"security guard gatekeeper watchman patrol night shift duty post incident report gate"},
    {"nco":"5414","sector":"Security","title":"Security Guard","cat":"Security & Facility","loc":"Bangalore","sal":"₹11000-17000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Allied Security","vehicle":"no","migrant":"yes","skills":"security guard night shift patrol gate entry exit visitor log access duty IT park tech"},
    {"nco":"9112","sector":"Security","title":"Office Boy / Peon","cat":"Security & Facility","loc":"Delhi","sal":"₹8000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"8th pass","exp":"0-2 yrs","co":"MNC Office","vehicle":"no","migrant":"yes","skills":"office boy peon filing tea coffee errand courier photocopy scan attendance register chaprassi support"},
    {"nco":"9112","sector":"Security","title":"Housekeeping Staff (Hotel)","cat":"Security & Facility","loc":"Goa","sal":"₹9000-15000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Marriott","vehicle":"no","migrant":"yes","skills":"housekeeping room cleaning hotel bed linen bathroom vacuum mopping trolley guest service daily"},
    {"nco":"9112","sector":"Security","title":"Hospital Housekeeping","cat":"Security & Facility","loc":"Hyderabad","sal":"₹9000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"0-2 yrs","co":"Apollo","vehicle":"no","migrant":"yes","skills":"hospital housekeeping cleaning ward OT ICU patient area biohazard infection control mop sanitize"},
    {"nco":"5414","sector":"Security","title":"Parking Attendant","cat":"Security & Facility","loc":"Mumbai","sal":"₹8000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"ParkPlus","vehicle":"no","migrant":"yes","skills":"parking attendant vehicle in out log token mall commercial complex shift security challan"},
]

# ══ MANUFACTURING — NCO 7223 ══
MANUFACTURING = [
    {"nco":"7223","sector":"Manufacturing","title":"Machine Operator (CNC)","cat":"Manufacturing","loc":"Pune","sal":"₹15000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"ITI-Diploma","exp":"1-4 yrs","co":"Bajaj Auto","vehicle":"two-wheeler","migrant":"yes","skills":"machine operator CNC lathe milling drilling pressing production line manufacturing factory shift quality"},
    {"nco":"7223","sector":"Manufacturing","title":"Machine Operator","cat":"Manufacturing","loc":"Coimbatore","sal":"₹14000-20000/mo","sal_type":"monthly","work_type":"Full-time","edu":"ITI-Diploma","exp":"1-3 yrs","co":"Textile Factory","vehicle":"two-wheeler","migrant":"yes","skills":"machine operator lathe milling production line factory shift quality maintenance CNC"},
    {"nco":"9321","sector":"Manufacturing","title":"Packing / Packaging Worker","cat":"Manufacturing","loc":"Surat","sal":"₹8000-13000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Factory","vehicle":"no","migrant":"yes","skills":"packing packaging sealing labelling carton box product wrapping weighing palletizing dispatch warehouse"},
    {"nco":"7543","sector":"Manufacturing","title":"Quality Checker (QC)","cat":"Manufacturing","loc":"Chennai","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"Hyundai","vehicle":"two-wheeler","migrant":"no","skills":"quality checker QC inspection visual checking measurement defect rejection sampling production line standard"},
    {"nco":"7233","sector":"Manufacturing","title":"Fitter (ITI)","cat":"Manufacturing","loc":"Nashik","sal":"₹15000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"ITI-Diploma","exp":"2-5 yrs","co":"Bosch India","vehicle":"two-wheeler","migrant":"yes","skills":"fitter ITI mechanical fitting assembly nuts bolts spanner alignment measurement tolerance maintenance factory"},
    {"nco":"8344","sector":"Manufacturing","title":"Forklift Operator","cat":"Manufacturing","loc":"Pune","sal":"₹600-900/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"2-4 yrs","co":"Mahindra","vehicle":"no","migrant":"no","skills":"forklift operator warehouse loading unloading material handling hydraulic lift pallet rack storage safety"},
]

# ══ BEAUTY & WELLNESS — NCO 5141, 5142 ══
BEAUTY = [
    {"nco":"5142","sector":"Wellness","title":"Beautician","cat":"Beauty & Wellness","loc":"Hyderabad","sal":"₹600-1000/day","sal_type":"daily","work_type":"Full-time","edu":"10th pass","exp":"1-3 yrs","co":"VLCC","vehicle":"no","migrant":"no","skills":"beautician salon facial waxing threading makeup hair colour nail pedicure manicure bridal beauty parlour"},
    {"nco":"5141","sector":"Wellness","title":"Barber","cat":"Beauty & Wellness","loc":"Mumbai","sal":"₹500-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Jawed Habib","vehicle":"no","migrant":"yes","skills":"barber gents salon haircut shave beard trimming razor clipper grooming head massage fade undercut styling naai"},
    {"nco":"5141","sector":"Wellness","title":"Barber","cat":"Beauty & Wellness","loc":"Delhi","sal":"₹500-900/day","sal_type":"daily","work_type":"Full-time","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"barber haircut shave beard trim razor clipper gents salon naai head massage styling"},
    {"nco":"5142","sector":"Wellness","title":"Mehndi Artist","cat":"Beauty & Wellness","loc":"Jaipur","sal":"₹500-900/day","sal_type":"daily","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"Self-employed","vehicle":"no","migrant":"no","skills":"mehndi henna artist bridal wedding design pattern application festive event"},
    {"nco":"5141","sector":"Wellness","title":"Hair Stylist","cat":"Beauty & Wellness","loc":"Delhi","sal":"₹12000-20000/mo","sal_type":"monthly","work_type":"Full-time","edu":"Diploma Beauty","exp":"1-3 yrs","co":"Naturals Salon","vehicle":"no","migrant":"yes","skills":"hair styling colour cut blowdry treatment keratin smoothening highlights salon"},
    {"nco":"5141","sector":"Wellness","title":"Mobile Barber","cat":"Beauty & Wellness","loc":"Hyderabad","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"No requirement","exp":"1-3 yrs","co":"UrbanClap","vehicle":"two-wheeler","migrant":"yes","skills":"barber haircut shave beard mobile home visit doorstep gig"},
]

# ══ HEALTHCARE (PARA) — NCO 3221 ══
HEALTHCARE = [
    {"nco":"2221","sector":"Healthcare","title":"Staff Nurse","cat":"Healthcare (Para)","loc":"Mumbai","sal":"₹25000-40000/mo","sal_type":"monthly","work_type":"Full-time","edu":"Graduate","exp":"1-3 yrs","co":"Fortis","vehicle":"no","migrant":"no","skills":"nurse nursing patient care ward ICU medication injection vitals monitoring hospital GNM BSc nursing"},
    {"nco":"3221","sector":"Healthcare","title":"Home Nursing Aide","cat":"Healthcare (Para)","loc":"Delhi","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Portea","vehicle":"no","migrant":"yes","skills":"nursing aide patient care elder bed sore feeding injection vitals blood pressure home visit ANM helper"},
    {"nco":"3221","sector":"Healthcare","title":"ANM / Health Worker","cat":"Healthcare (Para)","loc":"Ranchi","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"1-3 yrs","co":"Government","vehicle":"two-wheeler","migrant":"no","skills":"ANM community health worker vaccination immunization maternal child health village rural public health ASHA"},
    {"nco":"3221","sector":"Healthcare","title":"ASHA Worker","cat":"Healthcare (Para)","loc":"Patna","sal":"₹8000-12000/mo","sal_type":"monthly","work_type":"Part-time","edu":"10th pass","exp":"0-2 yrs","co":"NHM Bihar","vehicle":"no","migrant":"no","skills":"community health ASHA incentive scheme village health worker rural"},
    {"nco":"3221","sector":"Healthcare","title":"Patient Care Attendant","cat":"Healthcare (Para)","loc":"Delhi","sal":"₹11000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"0-2 yrs","co":"Fortis Hospital","vehicle":"no","migrant":"yes","skills":"patient care ward ICU attendant hospital nursing feeding bathing"},
    {"nco":"3212","sector":"Healthcare","title":"DMLT Lab Technician","cat":"Healthcare (Para)","loc":"Hyderabad","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"1-3 yrs","co":"Diagnostic Lab","vehicle":"two-wheeler","migrant":"no","skills":"lab technician DMLT blood sample collection pathology diagnostic test CBC haemogram urine stool"},
]

# ══ BPO & TELECALLING — NCO 4222 ══
BPO = [
    {"nco":"4222","sector":"ITES","title":"Telecaller (Outbound)","cat":"BPO & Telecalling","loc":"Mumbai","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Concentrix","vehicle":"no","migrant":"no","skills":"telecaller outbound calling customer leads sales pitch follow up CRM Hindi English targets BPO"},
    {"nco":"4222","sector":"ITES","title":"Customer Care Executive","cat":"BPO & Telecalling","loc":"Hyderabad","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Wipro BPO","vehicle":"no","migrant":"no","skills":"customer care inbound calling support queries resolution CRM ticket telecaller"},
    {"nco":"4132","sector":"ITES","title":"Data Entry Operator","cat":"BPO & Telecalling","loc":"Patna","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Data Co","vehicle":"no","migrant":"no","skills":"data entry typing accuracy computer MS Office Excel Word form filling database basic computer"},
    {"nco":"4222","sector":"ITES","title":"Telecaller (Hindi)","cat":"BPO & Telecalling","loc":"Delhi","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-1 yrs","co":"IndiaMart","vehicle":"no","migrant":"yes","skills":"outbound calling Hindi leads CRM calling target follow up sales BPO"},
    {"nco":"4221","sector":"ITES","title":"Telesales Executive","cat":"BPO & Telecalling","loc":"Bangalore","sal":"₹14000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"1-3 yrs","co":"Policy Bazaar","vehicle":"no","migrant":"yes","skills":"telesales insurance leads target calling premium policy BPO"},
    {"nco":"4221","sector":"ITES","title":"Collection Caller","cat":"BPO & Telecalling","loc":"Lucknow","sal":"₹11000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Creditas","vehicle":"no","migrant":"yes","skills":"collection calling recovery EMI overdue payment BPO"},
    {"nco":"4132","sector":"ITES","title":"Back Office Executive","cat":"BPO & Telecalling","loc":"Chennai","sal":"₹10000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Mphasis","vehicle":"no","migrant":"yes","skills":"back office data processing documentation Excel typing accuracy"},
]

# ══ FIELD SALES & RETAIL — NCO 5220 ══
FIELD_SALES = [
    {"nco":"5220","sector":"Retail","title":"Field Sales Executive","cat":"Field Sales & Retail","loc":"Mumbai","sal":"₹15000-25000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"1-3 yrs","co":"HUL","vehicle":"two-wheeler","migrant":"no","skills":"field sales FMCG door to door retail beat territory distributor outlet visit target order booking"},
    {"nco":"5220","sector":"Retail","title":"Shop Sales Assistant","cat":"Field Sales & Retail","loc":"Ahmedabad","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"10th pass","exp":"0-2 yrs","co":"Retail Store","vehicle":"no","migrant":"no","skills":"shop salesman retail store customer garment clothing footwear electronics showroom dukaan sales"},
    {"nco":"5220","sector":"Retail","title":"Insurance Sales Agent","cat":"Field Sales & Retail","loc":"Indore","sal":"₹12000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"LIC","vehicle":"two-wheeler","migrant":"no","skills":"insurance sales agent LIC policy premium renewal lead customer meeting target commission"},
    {"nco":"5223","sector":"Retail","title":"Grocery Store Helper","cat":"Field Sales & Retail","loc":"Jaipur","sal":"₹8000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Local Kirana","vehicle":"no","migrant":"yes","skills":"grocery store stocking billing customer kirana shop retail"},
    {"nco":"5223","sector":"Retail","title":"Door to Door Sales Agent","cat":"Field Sales & Retail","loc":"Chennai","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Eureka Forbes","vehicle":"two-wheeler","migrant":"yes","skills":"door to door sales product demonstration customer visit field target"},
    {"nco":"5223","sector":"Retail","title":"Pharma Sales Rep (Entry)","cat":"Field Sales & Retail","loc":"Pune","sal":"₹14000-22000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"0-2 yrs","co":"Sun Pharma","vehicle":"two-wheeler","migrant":"yes","skills":"pharma sales doctor clinic visit medical rep prescription target territory"},
    {"nco":"3322","sector":"Retail","title":"MicroFinance Field Agent","cat":"Field Sales & Retail","loc":"Lucknow","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"12th pass","exp":"1-3 yrs","co":"Bandhan Bank","vehicle":"two-wheeler","migrant":"no","skills":"microfinance collection field visit rural village repayment group meeting"},
]

# ══ STREET VENDING — NCO 5244 ══
STREET_VENDING = [
    {"nco":"5244","sector":"Informal Trade","title":"Street Food Vendor","cat":"Street Vending","loc":"Delhi","sal":"₹15000-30000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"street food vendor chaat pani puri momos rolls vada pav bhel puri cart stall customer thela hawker food"},
    {"nco":"5244","sector":"Informal Trade","title":"Street Food Vendor","cat":"Street Vending","loc":"Mumbai","sal":"₹15000-30000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"street food vendor vada pav cutting chai pav bhaji bhel puri cart customer Mumbai hawker"},
    {"nco":"5244","sector":"Informal Trade","title":"Fruit Cart Vendor","cat":"Street Vending","loc":"Bangalore","sal":"₹10000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"yes","skills":"fruit cart vendor fresh cut pineapple mango papaya watermelon street push cart seasonal daily"},
    {"nco":"5244","sector":"Informal Trade","title":"Newspaper / Milk Agent","cat":"Street Vending","loc":"Pune","sal":"₹8000-14000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Self-employed","vehicle":"two-wheeler","migrant":"no","skills":"newspaper delivery morning milk vendor route early morning regular customer distribution agent"},
    {"nco":"5244","sector":"Informal Trade","title":"Pan / Cigarette Shop","cat":"Street Vending","loc":"Mumbai","sal":"₹15000-25000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"paan shop pan cigarette tobacco betel nut retail customer daily small shop local neighbourhood"},
    {"nco":"5244","sector":"Informal Trade","title":"Chaat Vendor (Cart)","cat":"Street Vending","loc":"Lucknow","sal":"₹12000-20000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"No requirement","exp":"0-2 yrs","co":"Self","vehicle":"no","migrant":"yes","skills":"chaat pani puri bhel street food cart thela vendor selling"},
    {"nco":"5244","sector":"Informal Trade","title":"Momos Stall Operator","cat":"Street Vending","loc":"Noida","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Gig-Daily","edu":"No requirement","exp":"0-1 yrs","co":"Self","vehicle":"no","migrant":"yes","skills":"momos stall steam fried street food NE cart selling vendor"},
]

# ══ WASTE & RECYCLING — NCO 9611 ══
WASTE = [
    {"nco":"9611","sector":"Waste Management","title":"Waste Picker / Ragpicker","cat":"Waste & Recycling","loc":"Delhi","sal":"₹6000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Self-employed","vehicle":"no","migrant":"yes","skills":"waste picker ragpicker plastic paper metal scrap kabaadi collection segregation recycling environment informal"},
    {"nco":"9611","sector":"Waste Management","title":"Scrap Dealer Helper","cat":"Waste & Recycling","loc":"Mumbai","sal":"₹7000-12000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"Kabaadi Shop","vehicle":"two-wheeler","migrant":"yes","skills":"scrap dealer kabaadi wala plastic paper metal glass collection sorting weighing recycling shop helper"},
    {"nco":"9611","sector":"Waste Management","title":"Sanitation Worker","cat":"Waste & Recycling","loc":"Delhi","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"MCD","vehicle":"no","migrant":"yes","skills":"sanitation worker garbage collection dustbin sweeping cleaning public toilet sewer municipal worker safai"},
    {"nco":"9611","sector":"Waste Management","title":"Sanitation Worker","cat":"Waste & Recycling","loc":"Mumbai","sal":"₹12000-18000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-1 yrs","co":"BMC","vehicle":"no","migrant":"yes","skills":"sanitation worker garbage collection dustbin sweeping road cleaning municipal BMC safai karmachari"},
    {"nco":"9611","sector":"Waste Management","title":"E-Waste Collector","cat":"Waste & Recycling","loc":"Delhi","sal":"₹10000-16000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"0-2 yrs","co":"Attero","vehicle":"two-wheeler","migrant":"yes","skills":"e-waste collector old computer mobile TV appliance pickup disassembly circuit board recycling collection"},
    {"nco":"9611","sector":"Waste Management","title":"Kabadi Dealer (Wholesale)","cat":"Waste & Recycling","loc":"Bangalore","sal":"₹15000-25000/mo","sal_type":"monthly","work_type":"Full-time","edu":"No requirement","exp":"2-4 yrs","co":"Self","vehicle":"two-wheeler","migrant":"yes","skills":"kabaadi scrap wholesale plastic metal paper recycling collection weighing dealer"},
]
