"""
WorkMatch Pro v4 — CNN Training Pairs
Over 70 query-category pairs for the CNN classifier.
"""

RAW_PAIRS = [
    ("plumber water pipe tap fitting repair bathroom kitchen", "Plumbing"),
    ("drainage nala cleaning underground sewer municipal", "Plumbing"),
    ("geyser installation repair solar water heater", "Plumbing"),
    ("pipe leak burst fitting nal thik plumber", "Plumbing"),
    ("electrician wiring MCB switch socket fan inverter light fitting repair", "Electrical Work"),
    ("solar panel installation rooftop wiring inverter battery", "Electrical Work"),
    ("lineman overhead power line transformer distribution", "Electrical Work"),
    ("carpenter furniture door window wood plywood modular kitchen wardrobe", "Carpentry"),
    ("shuttering formwork centering RCC column slab construction", "Carpentry"),
    ("modular kitchen installation cabinet drawer hinge fitting laminate", "Carpentry"),
    ("AC air conditioner repair gas compressor cooling HVAC split window", "AC & Appliance Repair"),
    ("washing machine refrigerator geyser appliance repair technician", "AC & Appliance Repair"),
    ("mobile phone screen battery repair PCB soldering Android", "AC & Appliance Repair"),
    ("CCTV installation DVR NVR IP camera biometric access control", "AC & Appliance Repair"),
    ("painter wall interior exterior emulsion putty primer brush roller", "Painting"),
    ("waterproofing terrace roof leakage chemical membrane sealant", "Painting"),
    ("mason bricklaying plastering cement wall tiling rajmistri construction", "Masonry"),
    ("site labourer mazdoor cement mixing sand loading digging excavation", "Masonry"),
    ("bar bender rod binder steel rebar RCC column beam slab iron", "Masonry"),
    ("welder MIG TIG arc gas cutting fabrication steel workshop", "Masonry"),
    ("delivery rider bike Swiggy Zomato food GPS route doorstep gig", "Gig Delivery"),
    ("Amazon flex Flipkart parcel two-wheeler last mile logistics OTP", "Gig Delivery"),
    ("Blinkit quick commerce 10-minute grocery dark store bike", "Gig Delivery"),
    ("personal driver car LMV GPS city outstation employer family", "Driver"),
    ("cab driver Ola Uber taxi app GPS passenger airport corporate", "Driver"),
    ("truck driver HMV lorry tipper highway freight national permit", "Driver"),
    ("auto rickshaw three-wheeler CNG city meter app passenger", "Driver"),
    ("maid cleaning cooking mopping sweeping washing dishes laundry", "Domestic (Cleaning)"),
    ("part-time bai morning ghar jhadu pocha bartan utensils 2 hours", "Domestic (Cleaning)"),
    ("deep cleaning sofa carpet bathroom kitchen post-construction", "Domestic (Cleaning)"),
    ("home cook Indian food roti sabzi dal rice biryani family meals", "Domestic (Cook/Care)"),
    ("babysitter nanny childcare infant toddler school pickup caring", "Domestic (Cook/Care)"),
    ("elder care senior attendant bed-ridden medication nursing aide", "Domestic (Cook/Care)"),
    ("restaurant hotel kitchen cook food curry tandoor marination", "Food & Hospitality"),
    ("dhaba cook highway roadside roti dal makhani Punjabi", "Food & Hospitality"),
    ("waiter steward food serving table order restaurant hotel banquet", "Food & Hospitality"),
    ("farm worker khet mazdoor crop harvest sow plant weed field", "Agriculture (Crops)"),
    ("tractor operator ploughing tilling combine harvester machine", "Agriculture (Crops)"),
    ("pesticide spray chemical crop protection pump field agriculture", "Agriculture (Crops)"),
    ("dairy farm cow buffalo milk milking fodder feeding care Amul", "Agriculture (Livestock)"),
    ("poultry chicken broiler egg farm cleaning feeding vaccination", "Agriculture (Livestock)"),
    ("vegetable fruit vendor thela cart wholesale retail mandi", "Agriculture (Vendor)"),
    ("fish monger macchi seller market wholesale cleaning gutting", "Agriculture (Vendor)"),
    ("tailor darzi stitching sewing cutting blouse salwar kurta silai", "Apparel & Textile"),
    ("garment factory sewing machine textile cutting export production", "Apparel & Textile"),
    ("embroidery chikankari zardozi hand work thread needle craft", "Apparel & Textile"),
    ("weaving handloom power loom silk cotton saree banarasi bunai", "Apparel & Textile"),
    ("security guard watchman patrol entry exit visitor access control night", "Security & Facility"),
    ("housekeeping hotel hospital room cleaning bed linen service", "Security & Facility"),
    ("office boy peon tea coffee errand filing photocopy chaprassi", "Security & Facility"),
    ("machine operator CNC lathe milling factory production line ITI", "Manufacturing"),
    ("packing packaging sealing labelling carton box weighing dispatch", "Manufacturing"),
    ("quality checker QC inspection defect rejection sampling line", "Manufacturing"),
    ("beautician facial waxing threading makeup hair colour nail pedicure salon", "Beauty & Wellness"),
    ("barber haircut shave beard trimming razor clipper naai head massage", "Beauty & Wellness"),
    ("mehndi henna artist bridal wedding design application festive", "Beauty & Wellness"),
    ("nurse nursing patient care ward ICU medication vitals hospital GNM", "Healthcare (Para)"),
    ("home nursing aide elder patient injection blood pressure visit", "Healthcare (Para)"),
    ("ANM community health vaccination maternal child village rural ASHA", "Healthcare (Para)"),
    ("telecaller outbound calling sales leads CRM Hindi English targets BPO", "BPO & Telecalling"),
    ("customer care inbound support queries resolution CRM ticket", "BPO & Telecalling"),
    ("data entry typing accuracy MS Office Excel database form filling", "BPO & Telecalling"),
    ("field sales FMCG beat territory distributor outlet order booking", "Field Sales & Retail"),
    ("insurance agent LIC policy premium renewal lead commission target", "Field Sales & Retail"),
    ("street food vendor chaat momos vada pav rolls cart thela hawker", "Street Vending"),
    ("pan cigarette shop tobacco betel nut retail neighbourhood", "Street Vending"),
    ("waste picker ragpicker plastic paper metal scrap recycling kabaadi", "Waste & Recycling"),
    ("sanitation worker garbage dustbin sweeping municipal safai karmachari", "Waste & Recycling"),
]
